# Generated by Django 2.0.2 on 2018-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180216_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='cluster_id',
            field=models.CharField(max_length=10),
        ),
    ]
