# Generated by Django 2.0.2 on 2018-02-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180216_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='assignment_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='cluster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Clusters'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='full_text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='preprocessed_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
