# Generated by Django 2.0.2 on 2018-02-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180216_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='cluster_id',
        ),
        migrations.DeleteModel(
            name='Clusters',
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
